// DIFFFERNT TYPE OF FUNCTION [IIFE] -> IMMEDIATELY INVOKED FUNCTION EXPRESSION

// IMMEDIATELY INVOKED FUNCTION EXPRESSION 
// EXECUATED ONLY ONCE 

// NOW THIS IS EXPRESSION 
// (Function(name){
//     console.log("Hello " ,(name));
// })("IIFE") // TO EXECUTE IT AT LAST PUT ()