// JAVASCRIPT DOM {DOCUMENT OBECT MODEL}
// CREATED BY BROWER AS THE HTML LOAD INTO THE ANOTHER

// BROWER CREATE OBJECT OF HTML CALLED 'DOCUMENT OBJECT'

// IN DOCUMENT OBJECT THERE IS MODEL OF COMPLETE HTML IN 
// TREE LIKE STRUCTURE

console.log(document.get)

